version: '3.0'

services:
  nalogovichokbot:
    container_name: taxbot-dev
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: ./Dockerfile

    networks:
      - clickhouse_network
    command: pipenv run python app.py -d
  
  clickhouse-server:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server
    networks:
      - clickhouse_network
    ports:
      - "18123:8123"
      - "19000:9000"
      - "9009:9009"
    environment:
      - CLICKHOUSE_CONFIG_FILE=/etc/clickhouse-server/config.xml
networks:
  clickhouse_network: 